- name: Update apt sources list to use official Ubuntu mirrors
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^(deb|deb-src).*hetzner.com'
    state: absent

- name: Add official Ubuntu mirrors to sources list
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list
    block: |
      deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
    state: present

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Install Python and python3-pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: Replace the hostname entry with our own
  lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: root
    env: yes
    job: ""
