- name: Create DNS config file for dnsmasq
  ansible.builtin.copy:
    dest: /etc/dnsmasq.conf
    content: |
      listen-address=127.0.0.1
      listen-address=10.0.0.1
      bind-interfaces
      server=8.8.8.8
      server=8.8.4.4
    owner: root
    group: root
    mode: '0644'

- name: Install dnsmasq package
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Enable and start dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true
    state: started

- name: Add firewall rule to route DNS traffic through VPN
  command: iptables -t nat -A PREROUTING -s 10.0.0.0/24 -p udp --dport 53 -j DNAT --to-destination 10.0.0.1

- name: Restart dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
